export const CACHE_PATH = {
  USERSHOME: {
    DEFAULT: 'USERSHOME_DEFAULT',
    HOTELS: 'USERSHOME_HOTELS',
    HOTELS_CHAIN: 'USERSHOME_HOTELS_CHAIN',
  },
  HOTELS: {
    DEFAULT: 'HOTELS_DEFAULT',
  },
  HOTELS_CHAIN: {
    DEFAULT: 'HOTELS_CHAIN_DEFAULT',
    POLICY: 'HOTELS_CHAIN_POLICY',
  },
} as const
